[POAE7-347] Provide PMem chunkoutputStream/ChunkInputStream API based on Spark memory spill scenario.
Intel-bigdata/OAP pull request #1415
Opened 2020-07-02 05:59 UTC by yma11

## What changes were proposed in this pull request?

1) incrementally write to single chunkoutputstream

2) track writing position in chunkoutput stream

3) provide NioBufferedInputStream like API for chunkInputStream

4) corresponding UT

## How was this patch tested?

UT

2020-07-02 06:05 UTC, yma11 commented
@winningsix @yeyuqiang @xieqi, please take a look this PR. Thanks.

2020-09-11 07:57 UTC, winningsix requested changes

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
> +                System.out.println("Read data from real file.");
You mean log? Debug level please.

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
>      private ByteBuffer remainingBuffer;
Hmm, it's inconsistent buffer between read buffer and PMEM chunk, Considering we're in memory already, can we use a memory holder instead of a read buffer here to avoid one extra copy?

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
> +            if( metaData.isHasDiskData() == false ) {
if(!metaData.isHasDiskData())

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
> +                if(offset < originChunkOffset)
if(offset < originChunkOffset) {
                    offsetInChunk += readedDataSize;
                 } else {
                    offsetInChunk = 0;
                    chunkID++;
                }

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
> +        while(size < totalRequest) {
We don't need this while loop any more.

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
> +            else
It's very easy to make mistakes. Please ALWAYS add {} for if-else.

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
> +            if (remainingDiscardSize <= 0) {
use if-else

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
> +        // delete file
Rmove this.

2020-09-11 07:57 UTC, winningsix commented on oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
> +        long discardedSize = position() + remainingBuffer.position() - truncatePosition;
What if discardSize is negative?

2020-09-11 07:57 UTC, winningsix commented
@yma11 , you can format your code in IDEA directly.

2020-09-15 02:26 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkReader.java
> +    protected byte[] readFromPMem(PMemPhysicalAddress pMemPhysicalAddress, int offsetInChunk, int remainingRequest) {
In current PMemBlkChunkReader, 'protected int readFromPMem(PMemPhysicalAddress pMemPhysicalAddress, ByteBuffer data)' is still used. I think it's okay to both API exist.

2020-09-15 02:40 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
> +        if (!refill()) {
Logic in these methods are referred from NioBufferedInputStream in Spark,  maybe keep as this also be okay?

2020-09-15 03:21 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
> +        long discardedSize = position() + remainingBuffer.position() - truncatePosition;
add check for this condition.

2020-09-15 03:21 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
> +            if (remainingDiscardSize <= 0) {
updated.

2020-09-15 03:23 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
> +        while(size < totalRequest) {
No, we need this loop in this scenario. TotalRequest = 1024, but in this chunk, there is only 1000 bytes, we will need to use this loop to read 2 chunks to get 1024 bytes.

2020-09-15 03:41 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
>      private ByteBuffer remainingBuffer;
Will refine this with dedicate PR.

2020-09-15 05:42 UTC, winningsix commented
LGTM. cc @dongxin @yeyuqiang

2020-09-15 05:42 UTC, winningsix approved these changes

2020-09-15 06:24 UTC, merged