[oap-common][POAE7-347]Stream API for PMem storage store
Intel-bigdata/OAP pull request #1719
Opened 2020-09-15 07:36 UTC by yma11

## What changes were proposed in this pull request?

Provide stream API for PMem storage store

## How was this patch tested?

Corresponding UT added.

2020-09-15 07:37 UTC, yma11 commented
@winningsix @yeyuqiang @jikunshang Please take a review, thanks.

2020-09-16 04:34 UTC, yma11 commented
@winningsix @yeyuqiang @jikunshang Travis passed, please take a review and help merge it. Thanks.

2020-09-16 07:27 UTC, jikunshang requested changes
There are some code style issues, like indent size, apache lisence. Please add maven code style check plugin in pom file and fix them.

2020-09-16 07:27 UTC, jikunshang commented on pom.xml
> +        <jmh.version>1.23</jmh.version>
can we move these properties to `oap-common/pom.xml` ？

2020-09-16 07:27 UTC, jikunshang commented on oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemKVDatabase.java
> +        boolean forceCreate = !isCreated(path);
Do we need `synchronized ` here?

2020-09-16 07:27 UTC, jikunshang commented on oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/benchmark/PMemBlkPerfTool.java
> +package com.intel.oap.common.storage.pmemblk.benchmark;
This class is better to move to `test` dir.

2020-09-16 07:27 UTC, jikunshang commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkWriter.java
> +//        this.remainingBuffer = ByteBuffer.allocateDirect(pMemManager.getChunkSize());
Please remove if it's unnecessary.

2020-09-16 07:27 UTC, jikunshang commented on oap-common/src/main/java/com/intel/oap/common/unsafe/PMemMemoryMapper.java
> +    public static native void pmemMemcpy(long pmemAddress, byte[] src, long length);
Please add notes as other methods.

2020-09-16 07:40 UTC, yma11 commented on .travis.yml
> +dist: bionic
because libpmemblk related dependencies can't be installed on trusty.

2020-09-16 07:45 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemManager.java
> +        PersistentMemoryPlatform.initialize(initialPath, initialSize , 0);
Currently it will initialize PMem using memkind as the space for raw data storage. and for the metastore type, yuqiang will use pmemblk to leverage pmemkv to store metadata, while memkind will use hashmap instead. This part may need change when other store backend added, like plasma or vmemcache.

2020-09-16 07:46 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindMetaStore.java
> +        pMemHashMap.remove(keyBuilder.toString());
No, the real release happens like this:
                PersistentMemoryPlatform.freeMemory(pMemPhysicalAddress.getBaseAddress());
                pMemManager.getStats().decreaseSize(pMemPhysicalAddress.getOffset());
                pMemMetaStore.removePhysicalAddress(logicalID, currentTrunkID);

2020-09-16 07:48 UTC, yma11 commented on pom.xml
> +        <jmh.version>1.23</jmh.version>
seems most of the version are defined in this base pom.xml

2020-09-16 07:50 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/benchmark/PMemBlkPerfTool.java
> +package com.intel.oap.common.storage.pmemblk.benchmark;
This is for pmemblk, maybe can be addressed in another PR.

2020-09-16 07:50 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkWriter.java
> +//        this.remainingBuffer = ByteBuffer.allocateDirect(pMemManager.getChunkSize());
done.

2020-09-16 07:53 UTC, yma11 commented on oap-common/src/main/java/com/intel/oap/common/unsafe/PMemMemoryMapper.java
> +    public static native void pmemMemcpy(long pmemAddress, byte[] src, long length);
This is for pmemblk usage, @yeyuqiang should update in his late PR.

2020-09-17 01:47 UTC, jikunshang approved these changes
LGTM. +1

2020-09-17 07:30 UTC, merged

2020-09-17 09:02 UTC, offthewall123 commented on .gitignore
> +*.iml
Do we need modify this file?