[POAE7-358] Spark integration: Memory Spill to PMem
Intel-bigdata/OAP pull request #1725
Opened 2020-09-17 08:16 UTC by yma11

## What changes were proposed in this pull request?

Enable memory spill to Pmem in Spark

1) update spark files BytesToBytesMap, UnsafeExternalSorter, UnsafeSorterSpillReader, UnsafeSorterSpillWriter, BlockManager to allow memory spill to PMem
2) provide PMemBlockObjectWriter as a PMem writer
3) add config entry to enable/disable memory spill to PMem.

## How was this patch tested?

UT and end-to-end test applied

2020-09-17 08:17 UTC, yma11 commented
@winningsix @jikunshang @yeyuqiang Please take a review, thanks.

2020-09-17 09:17 UTC, jikunshang commented
Can you create a Github issue for this PR?

2020-09-17 15:15 UTC, winningsix requested changes
Besides the code style issue (please change your IDE by importing code style template), please start a commit which includes the raw file of changed Spark files. It will reduce our burdens for back porting code across different versions.

2020-09-21 14:44 UTC, yma11 commented
@winningsix Addressed your comments so please review again.

2020-09-22 01:22 UTC, jikunshang commented on oap-spark/src/main/java/org/apache/spark/unsafe/map/BytesToBytesMap.java
> +    assert (dataPages.isEmpty());
revert this.

2020-09-22 01:25 UTC, yma11 commented on oap-spark/src/main/java/org/apache/spark/unsafe/map/BytesToBytesMap.java
> +    assert (dataPages.isEmpty());
But the later one is in correct format, right?

2020-09-22 01:45 UTC, jikunshang commented on oap-spark/src/main/java/org/apache/spark/unsafe/map/BytesToBytesMap.java
> +    assert (dataPages.isEmpty());
seems Spark is using the first one, which code format are you using? I remember idea code formater did have some difference with spark scala codestyle check plugin.

2020-09-22 01:59 UTC, yma11 commented on oap-spark/src/main/java/org/apache/spark/unsafe/map/BytesToBytesMap.java
> +    assert (dataPages.isEmpty());
Checked assert in other spark files, they use the first one. Let me revert it.

2020-09-22 02:01 UTC, yma11 commented on oap-spark/src/main/java/org/apache/spark/unsafe/map/BytesToBytesMap.java
> +    assert (dataPages.isEmpty());
Seems both conditions exist in Spark. Anyway,  I will revert it.

2020-09-22 05:53 UTC, yma11 commented
@jikunshang updated. Please take a review again. Thanks.

2020-09-22 07:02 UTC, jikunshang commented
I have added check style plugin in oap-common and oap-spark, you can refer or cherry-pick it in next PR. [link](https://github.com/jikunshang/OAP-1/commit/a89c601549a5a59e9754945eb56556499a3f650a)

2020-09-23 03:37 UTC, winningsix approved these changes

2020-09-23 03:37 UTC, merged