[POAE7-462] Enable externalDB to store CacheMetaInfo
Intel-bigdata/OAP pull request #1744
Opened 2020-09-23 05:26 UTC by offthewall123

## What changes were proposed in this pull request?

Enable externalDB to store CacheMetaInfo

## How was this patch tested?

E2E

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2020-09-23 07:23 UTC, offthewall123 commented on oap-cache/oap/src/main/spark3.0.0/scala/org/apache/spark/sql/execution/datasources/FilePartition.scala
> +    if (SparkEnv.get.conf.get(OapConf.OAP_EXTERNAL_CACHE_METADB_ENABLE) == true) {
Here's the difference from origin FilePartition.scala

2020-10-14 05:40 UTC, offthewall123 commented
@jikunshang @winningsix @yma11 @yeyuqiang Please take a review thanks.

2020-10-14 08:09 UTC, jikunshang requested changes
CI failed, please fix it.

2020-10-14 08:09 UTC, jikunshang commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/ParquetDataFiberReaderWriter.scala
> +      s"total = $total, header is $header")3
typo?

2020-10-14 09:59 UTC, offthewall123 commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/ParquetDataFiberReaderWriter.scala
> +      s"total = $total, header is $header")3
fixed

2020-10-15 00:25 UTC, jikunshang approved these changes
LGTM  +1.

2020-10-15 00:25 UTC, jikunshang commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
> +      case binary: BinaryDataFiberId => binary
can we merge case 1 and case 2 here?

2020-10-15 01:09 UTC, offthewall123 commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
> +      case binary: BinaryDataFiberId => binary
`BinaryDataFiberId` and `VectorDataFiberId` get report info by different ways, so i think can't merge it.

2020-10-15 01:23 UTC, jikunshang commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
> +      case binary: BinaryDataFiberId => binary
I mean like this:
`case fiberId: Binary | Vector => fiberId.report()`
But seems scala doesn't support, see [link](https://stackoverflow.com/questions/1837754/match-multiple-cases-classes-in-scala).
Anyway, just a suggestion.

2020-10-15 08:16 UTC, merged

2020-10-21 03:38 UTC, HongW2019 commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/internal/oap/OapConf.scala
> +    SqlConfAdapter.buildConf("spark.sql.oap.external.cache.metaDB.enable")
@offthewall123  To sync with Spark config style, we'd better modify .enable to .enabled,  PR #1802 and #1805 have made corresponding changes, pls pay attention when manually setting it in spark-defaults.conf.

2020-10-21 03:56 UTC, offthewall123 commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/internal/oap/OapConf.scala
> +    SqlConfAdapter.buildConf("spark.sql.oap.external.cache.metaDB.enable")
Got it.

2020-11-02 06:18 UTC, zhixingheyi-tian commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/internal/oap/OapConf.scala
> +    SqlConfAdapter.buildConf("spark.sql.oap.external.cache.metaDB.enable")
@offthewall123 

Would you avoid overriding Spark Source code FilePartition.scala?
Now FilePartition.scala is the only one we have not decoupled from Spark Source.

2020-11-02 06:30 UTC, offthewall123 commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/internal/oap/OapConf.scala
> +    SqlConfAdapter.buildConf("spark.sql.oap.external.cache.metaDB.enable")
@zhixingheyi-tian I think can decouple it, will submit a refactor pr.