[OAP-CACHE][POAE7-472]Branch 0.8 spark 2.4.x external db doc
Intel-bigdata/OAP pull request #1789
Opened 2020-10-13 09:51 UTC by offthewall123

## What changes were proposed in this pull request?

update user doc for external DB.

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2020-10-13 09:51 UTC, offthewall123 commented
@jikunshang @winningsix @yma11 @yeyuqiang  Please take a review thanks.

2020-10-13 13:27 UTC, jikunshang requested changes

2020-10-13 13:27 UTC, jikunshang commented on oap-cache/oap/docs/User-Guide.md
> +To support heterogeneous cluster(some nodes with Optane™ DC Persistent Memory, some without), we introduce an external DB to store cache meta info. Now support [Redis]("https://redis.io/"). Users nee
`launch a redis-server` use an official link?

2020-10-13 13:27 UTC, jikunshang commented on oap-cache/oap/docs/User-Guide.md
> +To support heterogeneous cluster(some nodes with Optane™ DC Persistent Memory, some without), we introduce an external DB to store cache meta info. Now support [Redis]("https://redis.io/"). Users nee
I don't think this part is clear for end users. Do you have any feedback? @winningsix @yeyuqiang @yma11

2020-10-14 01:23 UTC, yma11 commented on oap-cache/oap/docs/User-Guide.md
> +External DB stores cache's locality info, it will influence spark to schedule tasks according to cache locality. If there's no cache available, spark will fallback to schedule respecting HDFS localit
"Now support [Redis]("https://redis.io/"). Users need to [download and launch a redis-server]("https://redis.io/download"). " put this sentence at end of this paragraph and write it like "Currently we support Redis to provide the service and to launch a Redis server, please refer the [official guide]("https://redis.io/download"). "

2020-10-14 01:27 UTC, yma11 commented on oap-cache/oap/docs/User-Guide.md
>  ### Additional Cache Strategies
Highlight this feature works only with "external" cache strategy?

2020-10-14 02:25 UTC, offthewall123 commented on oap-cache/oap/docs/User-Guide.md
> +External DB stores cache's locality info, it will influence spark to schedule tasks according to cache locality. If there's no cache available, spark will fallback to schedule respecting HDFS localit
Modified, thanks.

2020-10-14 02:25 UTC, offthewall123 commented on oap-cache/oap/docs/User-Guide.md
>  ### Additional Cache Strategies
Yes, it should be added.

2020-10-14 02:28 UTC, offthewall123 commented on oap-cache/oap/docs/User-Guide.md
> +To support heterogeneous cluster(some nodes with Optane™ DC Persistent Memory, some without), we introduce an external DB to store cache meta info. Now support [Redis]("https://redis.io/"). Users nee
Yes, have changed it.

2020-10-14 02:47 UTC, jikunshang commented
LGTM.

2020-10-14 03:20 UTC, yma11 commented
LGTM+1.

2020-10-14 03:25 UTC, merged