[OAP-1631][Doc]Update MLlib Doc for OAP 1.0
Intel-bigdata/OAP pull request #1801
Opened 2020-10-16 04:27 UTC by HongW2019

## What changes were proposed in this pull request?

## How was this patch tested?

2020-10-16 04:29 UTC, HongW2019 commented
@xwu99 Please have a review and help merge it.

2020-10-16 06:03 UTC, xwu99 requested changes

2020-10-16 06:03 UTC, xwu99 commented on README.md
> +Optimized Analytics Package for Spark* Platform is under Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0).
You can highlight Apache 2.0 license.

2020-10-16 06:06 UTC, xwu99 commented on oap-mllib/README.md
> +You can use a pre-built JAR to get started, if you have finished [OAP-Installation-Guide](../docs/OAP-Installation-Guide.md), you can find compiled Intel MLlib jar `oap-mllib-x.x.x-with-spark-x.x.x.j
It's bad practice to use /root to install any of the software. it's better to use $HOME/miniconda2/envs/oapenv/oap_jars as in current user home directory.

2020-10-16 06:10 UTC, xwu99 commented on oap-mllib/README.md
> +You can use a pre-built JAR to get started, if you have finished [OAP-Installation-Guide](../docs/OAP-Installation-Guide.md), you can find compiled Intel MLlib jar `oap-mllib-x.x.x-with-spark-x.x.x.j
The principle is using root when only necessary. Install software to system-wide when only necessary.

2020-10-16 06:26 UTC, HongW2019 commented on oap-mllib/README.md
> +You can use a pre-built JAR to get started, if you have finished [OAP-Installation-Guide](../docs/OAP-Installation-Guide.md), you can find compiled Intel MLlib jar `oap-mllib-x.x.x-with-spark-x.x.x.j
@yao531441 Can we change the  /root to get a better practice?

2020-10-16 07:03 UTC, HongW2019 commented on README.md
> +LEGAL NOTICE: Your use of this software and any required dependent software (the "Software Package") is subject to the terms and conditions of the software license agreements for the Software Package
Have modified the font of Legal part to differentiate from OAP introduction. As for its location , intel Legal request "You must include at the top of the README file included with your distribution ......"

2020-10-16 07:35 UTC, yao531441 commented on oap-mllib/README.md
> +You can use a pre-built JAR to get started, if you have finished [OAP-Installation-Guide](../docs/OAP-Installation-Guide.md), you can find compiled Intel MLlib jar `oap-mllib-x.x.x-with-spark-x.x.x.j
@xwu99 Ok,we will recommend  usrs not to use the 'root' to install Conda.

2020-10-16 09:04 UTC, xwu99 requested changes

2020-10-16 09:06 UTC, xwu99 commented on docs/OAP-Installation-Guide.md
>  ```
no need to add extra / after a path, the same below.

2020-10-16 09:31 UTC, HongW2019 commented on docs/OAP-Installation-Guide.md
>  ```
Thanks for detailed suggestions.

2020-10-16 09:34 UTC, HongW2019 commented on docs/OAP-Installation-Guide.md
>  conda activate oapenv
Added.

2020-10-19 01:11 UTC, xwu99 requested changes

2020-10-19 01:11 UTC, xwu99 commented on README.md
> +OAP is a project to optimize Spark by providing optimized implementation of packages for various aspects including cache, shuffle, native sql engine, Mllib and so on. In this version, OAP contains th
sql => SQL

2020-10-19 01:11 UTC, xwu99 commented on docs/OAP-Installation-Guide.md
> +$ chmod 777 Miniconda2-latest-Linux-x86_64.sh
no need to to set extra permissions, just chmod +x

2020-10-19 01:11 UTC, xwu99 commented on docs/OAP-Installation-Guide.md
>  For changes to take effect, close and re-open your current shell.To test your installation,  run the command `conda list` in your terminal window. A list of installed packages appears if it has been
an extra space. your current shell.To => your current shell. To

2020-10-19 05:31 UTC, merged

2020-10-19 05:31 UTC, xwu99 commented
@HongW2019 thanks for your effort! merged!