[OAP-2068][POAE7-768][OAP-CACHE]PlasmaTimeOutWrapper
Intel-bigdata/OAP pull request #2091
Opened 2021-02-02 02:41 UTC by offthewall123

## What changes were proposed in this pull request?

Wrapper origin plasmaClient methods  with timeout mechanism.

## How was this patch tested?

E2E

2021-02-02 02:42 UTC, offthewall123 commented
@jikunshang @winningsix @yeyuqiang @xieqi Please take a review, thanks.

2021-02-02 03:10 UTC, jikunshang requested changes

2021-02-02 03:10 UTC, jikunshang commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
> +      case ie: InterruptedException =>
can we refactor like this?  
` case e: InterruptedException | ExecutionException  | TimeoutException =>     `
`logWarning("contains exception, type: " + e.getClass.getName + " message " + e.getMessage) `

2021-02-02 03:10 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/PlasmaTimeOutWrapper.java
> +    Method[] methods = plasmaClient.getClass().getDeclaredMethods();
hmmm, do we have some better way? or make this a global variable or map for better performance?

2021-02-02 05:15 UTC, offthewall123 commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
> +      val buf: ByteBuffer = PlasmaTimeOutWrapper.run("create", plasmaClient, executorService, paramValue, 3)
Added, original thougths is to avoid additional conf.

2021-02-02 05:16 UTC, offthewall123 commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
> +      case ie: InterruptedException =>
Seems can't case match in this way would cause "object java.util.concurrent.ExecutionException is not a value"

2021-02-02 05:16 UTC, offthewall123 commented on oap-cache/oap/src/main/java/org/apache/PlasmaTimeOutWrapper.java
> +    Method[] methods = plasmaClient.getClass().getDeclaredMethods();
Yes,can define a method map here, but i think it's strange to define it.We should get methods through reflect.

2021-02-02 05:31 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/PlasmaTimeOutWrapper.java
> +    Method[] methods = plasmaClient.getClass().getDeclaredMethods();
My question here is whether this `call` method will be called multi times. if so,  `getDeclaredMethods` may influence performance I guess.

2021-02-02 05:39 UTC, offthewall123 commented on oap-cache/oap/src/main/java/org/apache/PlasmaTimeOutWrapper.java
> +    Method[] methods = plasmaClient.getClass().getDeclaredMethods();
Yes, this method will be called many times.

2021-02-02 05:49 UTC, jikunshang commented on oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
> +      case ie: InterruptedException =>
try this:
`case e @ (_: InterruptedException  | _ : ExecutionException | _:TimeoutException ) => `

2021-02-02 06:11 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/PlasmaTimeOutWrapper.java
> +    Method[] methods = plasmaClient.getClass().getDeclaredMethods();
Could we pass some lambda function(wrap plasma methods)?

2021-02-04 00:54 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/spark/sql/execution/datasources/oap/filecache/PlasmaLambdaWrapper.java
> +package org.apache.spark.sql.execution.datasources.oap.filecache;
add license

2021-02-04 00:54 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/spark/sql/execution/datasources/oap/filecache/PlasmaLambdaWrapper.java
> +interface PlasmaLambdaWrapper {
rename to `PlasmaMethodWrapper` ?

2021-02-04 00:54 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/spark/sql/execution/datasources/oap/filecache/PlasmaLambdaWrapper.java
> +  public Object execute(PlasmaClient client, Object... param) {
can we define an extra class to replace `object[] param ` here?

2021-02-04 00:54 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/spark/sql/execution/datasources/oap/filecache/PlasmaLambdaWrapper.java
> +interface PlasmaLambdaWrapper {
Do we need to wrap connect method?

2021-02-04 01:08 UTC, offthewall123 commented on oap-cache/oap/src/main/java/org/apache/spark/sql/execution/datasources/oap/filecache/PlasmaLambdaWrapper.java
> +interface PlasmaLambdaWrapper {
`for ( i <- 0 until clientPoolSize) {
    try {
      plasmaClientPool(i) = new plasma.PlasmaClient(externalStoreCacheSocket, "", 0)
    } catch {
      case e: Exception =>
        logError(s"Error occurred when connecting to plasma server" + e.getMessage)
    }
  }`

Connect is just new PlasmaClient().

2021-02-04 01:14 UTC, offthewall123 commented on oap-cache/oap/src/main/java/org/apache/spark/sql/execution/datasources/oap/filecache/PlasmaLambdaWrapper.java
> +  public Object execute(PlasmaClient client, Object... param) {
Yes, we can, but i think it's too over-design.
1: Here param length is variable

2: At most 3 params
if define a class
plasmaParam {
  objectid
  timeout
  length
  isMetadata
}

will exist some empty value in the class.

2021-02-04 01:20 UTC, jikunshang commented on oap-cache/oap/src/main/java/org/apache/spark/sql/execution/datasources/oap/filecache/PlasmaLambdaWrapper.java
> +  public Object execute(PlasmaClient client, Object... param) {
some member could be null or default value if it's not used. it's over-design but more readable. For someone  don't have context, param here will be confusing.

2021-02-04 03:13 UTC, jikunshang commented
LGTM.

2021-02-04 03:14 UTC, merged